### PR TITLE
Add queries and mutations for booking services

### PR DESCRIPTION
**Pull request by abrahamUrquiola**

### CODE REVIEW

**Review by FreddyClaros — APPROVED** [review]
looks good to me

**Comment by FreddyClaros** [comment]
> looks good to me

but I think it need resolved some conflicts

**Comment by abrahamUrquiola** [comment]
I resolved the conflicts review please

**Review by FreddyClaros — APPROVED** [review]
looks good to me, good job

**Review by daylerVMT — APPROVED** [review]
looks good for my

**Comment by aquena-code** [comment]
It's ok Abraham

**Pull request merged**
